// src/pages/HomePage.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Row, Col } from 'antd';
import { CalendarOutlined, TeamOutlined, UserOutlined, ContactsOutlined, RobotOutlined } from '@ant-design/icons';
import styled from 'styled-components';

const HomeContainer = styled.div`
  padding: 60px 20px;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f0f2f5;
`;

const NavContainer = styled.div`
  width: 100%;
  max-width: 1200px;
`;

const NavButton = styled(Button)`
  height: 120px;
  font-size: 18px;
  font-weight: 500;
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  transition: all 0.3s ease;
  
  .anticon {
    font-size: 24px;
    margin-bottom: 8px;
  }
  
  &:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(24, 144, 255, 0.3);
  }
`;

const HomePage: React.FC = () => {
  const navigate = useNavigate();

  const navButtons = [
    {
      key: 'dayData',
      icon: <CalendarOutlined />,
      text: '今日数据',
      route: '/dayData'
    },
    {
      key: 'classData',
      icon: <TeamOutlined />,
      text: '班级数据',
      route: '/classData'
    },
    {
      key: 'teacherData',
      icon: <UserOutlined />,
      text: '教员数据',
      route: '/teacherData'
    },
    {
      key: 'studentData',
      icon: <ContactsOutlined />,
      text: '学员数据',
      route: '/studentData'
    },
    {
      key: 'aiSystem',
      icon: <RobotOutlined />,
      text: '智能中心',
      route: '/aiSystem'
    }
  ];

  const handleNavigate = (route: string) => {
    navigate(route);
  };

  return (
    <div style={{ padding: '20px', background: '#f0f2f5', minHeight: '100vh' }}>
      <h1 style={{ textAlign: 'center', marginBottom: '40px', color: '#1890ff' }}>
        数据中心管理系统
      </h1>
      <HomeContainer>
        <NavContainer>
          <Row gutter={[16, 16]} justify="center">
            {navButtons.map(button => (
              <Col span={4} key={button.key}>
                <NavButton
                  type="primary"
                  size="large"
                  block
                  onClick={() => handleNavigate(button.route)}
                  className="move-up"
                >
                  {button.icon}
                  {button.text}
                </NavButton>
              </Col>
            ))}
          </Row>
        </NavContainer>
      </HomeContainer>
    </div>
  );
};

export default HomePage;

// src/pages/HomePage.vue
<template>
  <div class="home-page">
    <h1 class="page-title">思政课堂学员自主学习系统</h1>
    <div class="home-container">
      <div class="nav-container">
        <a-row :gutter="16" justify="center">
          <a-col :span="4" v-for="button in navButtons" :key="button.key">
            <a-button
              type="primary"
              size="large"
              block
              class="nav-button"
              @click="handleNavigate(button.route)"
            >
              <a-icon :component="button.icon" />
              {{ button.text }}
            </a-button>
          </a-col>
        </a-row>
      </div>
    </div>
  </div>
</template>

<script>
import { CalendarOutlined, TeamOutlined, UserOutlined, ContactsOutlined, RobotOutlined } from '@ant-design/icons-vue'

export default {
  name: 'HomePage',
  components: {
    CalendarOutlined,
    TeamOutlined,
    UserOutlined,
    ContactsOutlined,
    RobotOutlined
  },
  data() {
    return {
      navButtons: [
        {
          key: 'dayData',
          icon: CalendarOutlined,
          text: '今日数据',
          route: '/dayData'
        },
        {
          key: 'classData',
          icon: TeamOutlined,
          text: '班级数据',
          route: '/classData'
        },
        {
          key: 'teacherData',
          icon: UserOutlined,
          text: '教员数据',
          route: '/teacherData'
        },
        {
          key: 'studentData',
          icon: ContactsOutlined,
          text: '学员数据',
          route: '/studentData'
        },
        {
          key: 'aiSystem',
          icon: RobotOutlined,
          text: '智能中心',
          route: '/aiSystem'
        }
      ]
    }
  },
  methods: {
    handleNavigate(route) {
      this.$router.push(route)
    }
  }
}
</script>

<style scoped>
.home-page {
  padding: 20px;
  background: #f0f2f5;
  min-height: 100vh;
}

.page-title {
  text-align: center;
  margin-bottom: 40px;
  color: #1890ff;
  font-size: 28px;
  font-weight: bold;
}

.home-container {
  padding: 60px 20px;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f0f2f5;
}

.nav-container {
  width: 100%;
  max-width: 1200px;
}

.nav-button {
  height: 120px;
  font-size: 18px;
  font-weight: 500;
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  transition: all 0.3s ease;
}

.nav-button .anticon {
  font-size: 24px;
  margin-bottom: 8px;
}

.nav-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(24, 144, 255, 0.3);
}
</style>
